spring:
  application:
    name: demo1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

  jwt:
    secret: your-very-long-secret-key-1234567890abcdefghijklmn
    expiration: 86400000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl